### ISSUE TITLE
ordering u,v,w velocity components

### ISSUE THREAD

**Issue by adokter** [jspaaks/baltrad-node#8]
https://github.com/jspaaks/baltrad-node/blob/558d7bb3db23aa32df9840e6a50b84e9c3eb0559/crave/testbaltrad.c#L432

The standard ordering of the velocity components is U,V,W, it seems it is now implemented as V,W,U

**Comment by jspaaks** [comment]
Currently, my code "https://github.com/jspaaks/baltrad-node/blob/558d7bb3db23aa32df9840e6a50b84e9c3eb0559/crave/testbaltrad.c#L429-L431" uses re-ordered arguments with order (2,0,1).

Corresponding code in your reference code "https://github.com/NLeSC/enram/blob/master/doc/vol2bird-adriaans-version-20140716/vol2birdprof_h5.c#L648-L650"  also uses out-of-order arguments (2,0,1).

Myabe the best thing to do is to change the root of the problem, i.e. the order here: "https://github.com/NLeSC/enram/blob/96339454b69dda864c6ae6cd93b65c6a34fcc5c4/ncradar/lib/vol2bird/libsvdfit.c#L68-L70"

I always thought that the out-of-order thing was intentional but now it seems it isn't (?). Let me know what you think is best.

**Comment by adokter** [comment]
Yes I used (1,2,0) order to get (U,V,W), and I think it's best to change the root of the problem in `svdfit`.

**Comment by jspaaks** [comment]
Changed the order in libsvbdfit. CLosing the issue
